---
default: &default
  cloud_name: <%= ENV.fetch("CLOUDINARY_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_SECRET") %>
  enhance_image_tag: true

development:
  <<: *default
  static_file_support: false

development:
  <<: *default
  static_file_support: true

test:
  <<: *default
  static_file_support: false


